language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9

sudo: false

before_install:
  - cp src/build/travis-toolchains.xml ~/.m2/toolchains.xml
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip
  - unzip -qq apache-maven-3.5.2-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.2
  - export PATH=$M2_HOME/bin:$PATH

install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -Dbasepom.it.skip=true -B -fae install
script: mvn -fae verify
